### ISSUE TITLE
Issue with path when generating instances

### ISSUE THREAD

**Issue by LettError** [LettError/designSpaceRoboFontExtension#100]
Generating instances by hitting the Generate Instances button in the instances tab. 

`Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 90, in sendEvent_
  File "/Applications/RoboFont_4.5b.app/Contents/Resources/lib/python3.12/vanilla/vanillaBase.py", line 539, in action_
    self.callback(sender)
  File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1497, in instancesEditorGenerateToolsCallback
    GenerateInstanceSheet(self.w, self.operator, instances)
  File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 253, in __init__
    instanceDescriptor.path = os.path.abspath(os.path.join(os.path.dirname(self.operator.path), instanceDescriptor.filename))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 90, in join
  File "<frozen genericpath>", line 164, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'`

**Comment by typemytype** [comment]
I guess here the `instance.filename` is still `None`, dont know how this happens, every new instance will or when the `filename` attribute is `None` a new file name is generated based on the prefs, family and style name
