### ISSUE TITLE
save designspace with unsaved open UFO

### ISSUE THREAD

**Issue by typemytype** [LettError/designSpaceRoboFontExtension#101]
popup a warning to save the unsaved UFO first 

```
Traceback (most recent call last):
  File "/Users/frederik/Documents/dev/typesupply/vanilla/Lib/vanilla/dialogs.py", line 181, in completionHandler_
    self._resultCallback(self._result)
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1969, in saveDesignspace
    sourceDescriptor.filename = os.path.relpath(sourceDescriptor.path, root)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 509, in relpath
ValueError: no path specified
Traceback (most recent call last):
  File "/Users/frederik/Documents/dev/typesupply/vanilla/Lib/vanilla/dialogs.py", line 181, in completionHandler_
    self._resultCallback(self._result)
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1969, in saveDesignspace
    sourceDescriptor.filename = os.path.relpath(sourceDescriptor.path, root)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 509, in relpath
ValueError: no path specified
```

**Comment by typemytype** [comment]
or save those unsaved UFO next to the designspace path? @LettError

**Comment by LettError** [comment]
Maybe DSE should show a dialog "Save the sources first"
