### ISSUE TITLE
`addLocationLabel()` and `addLocationLabelDescriptor()` are unsupported

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#105]
## Script:
```python
d = CurrentDesignspace()
d.addLocationLabel()
```
#### Error:
```
Traceback (most recent call last):
  File "<untitled>", line 2, in <module>
AttributeError: 'DesignspaceEditorOperator' object has no attribute 'addLocationLabel'. Did you mean: 'locationLabels'?
```

## Script:
```python
d = CurrentDesignspace()
d.addLocationLabelDescriptor()
```
#### Error:
```
Traceback (most recent call last):
  File "<untitled>", line 2, in <module>
AttributeError: 'DesignspaceEditorOperator' object has no attribute 'addLocationLabelDescriptor'
```

**Comment by typemytype** [comment]
this is a ufoOperator request to make them available (@LettError )

but you can do this for now:
```py
d = CurrentDesignspace()


label = d.writerClass.locationLabelDescriptorClass(
    name="foo bar",
    userLocation=dict()
)

d.locationLabels.append(label)```

**Comment by LettError** [comment]
Like this?
https://github.com/LettError/ufoProcessor/commit/e8593dc70b3a69b8748c2edb8b9c7915c691d168

**Comment by typemytype** [comment]
perfect! thanks
