### ISSUE TITLE
Error when loading extension

### ISSUE THREAD

**Issue by micahmicah** [LettError/designSpaceRoboFontExtension#16]
I'm currently getting the following error when I try to run DesignSpaceEditor, whether I'm opening a .designspace file or if I'm making a new one:

```
Traceback (most recent call last):
​  File "openDesignSpaceFile.py", line 10, in <module>
  File "/Users/micahbarrett/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1415, in __init__
  File "/Users/micahbarrett/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1673, in fillInterfaceWithDocumentData
  File "/Users/micahbarrett/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1526, in validate
  File "/Users/micahbarrett/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designspaceProblems/__init__.py", line 107, in checkEverything
  File "/Users/micahbarrett/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designspaceProblems/__init__.py", line 238, in checkSources
TypeError: newDefaultLocation() got an unexpected keyword argument 'bend'
```

causing the GUI to error like this:

![Screen Shot 2019-09-04 at 4 52 28 PM](https://user-images.githubusercontent.com/1166088/64301564-6f0eca00-cf34-11e9-9f75-3ceb131f7e61.png)

I wasn't having this problem yesterday and I'm not sure what I've done in the meantime that would cause this issue. Any insights would be greatly appreciated!

**Comment by jbmorizot** [comment]
It's because of a change that occured 12 days ago. Now the default location in the designSpaceProblem module call something from ufoProcessor. I installed the 1.8.dev5+gb3e0fde version but I have the same issue. You can download the commit before this change, and reinstall the extension, it should do the work.

**Comment by arrowtype** [comment]
I am also experiencing this issue, currently, and it is blocking me from working with both this extension and RoboFont Skateboard. I'll try the previous version and hope that I can workaround this for now.

**Comment by typemytype** [comment]
I guess this is fixed along the way... can not reproduce with the latest DS5 version see https://github.com/LettError/designSpaceRoboFontExtension/tree/dse2.0
