### ISSUE TITLE
RAnchor is not iterable

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#28]
Traceback raised:
https://github.com/LettError/designSpaceRoboFontExtension/blob/3c9640a3e450d02860c744880bc6c7e628dcdf97/DesignSpaceEditor.roboFontExt/lib/designspaceProblems/__init__.py#L484

```Traceback (most recent call last):
  File "openDesignSpaceFile.py", line 10, in <module>
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1566, in __init__
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1881, in fillInterfaceWithDocumentData
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1720, in validate
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designspaceProblems/__init__.py", line 155, in checkEverything
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designspaceProblems/__init__.py", line 446, in checkGlyphs
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designspaceProblems/__init__.py", line 484, in checkGlyph
TypeError: argument of type 'RAnchor' is not iterable
```

The following solves it on my end, but not sure if this was your intention:
`if not 'name' in dir(ad):`

**Comment by ryanbugden** [comment]
🙏
