### ISSUE TITLE
crash when opening from RF 4.3b

### ISSUE THREAD

**Issue by LettError** [LettError/designSpaceRoboFontExtension#29]
Hard RF crash when trying to open a designspace from the DSE menu.
```
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> Traceback (most recent call last):
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> File "lib/scripting/scriptTools.pyc", line 253, in _ScriptRunner
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> File "openDesignSpaceFile.py", line 10, in <module>
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> DesignSpaceEditor(path)
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1582, in __init__
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> self.updateLocations()
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1980, in updateLocations
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> self._updateLocation(instanceDescriptor, defaults)
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1989, in _updateLocation
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> for axisName in descriptor.location.keys():
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> AttributeError
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> :
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> 'NoneType' object has no attribute 'keys'
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> During handling of the above exception, another exception occurred:
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> Traceback (most recent call last):
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> File "/Applications/RoboFont_4.3_beta.app/Contents/Resources/lib/python3.7/vanilla/vanillaList.py", line 183, in tableView_objectValueForTableColumn_row_
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> return getattr(item, columnID)()
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 528, in instanceAxis_1
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> return self.getAxisValue(0)
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 520, in getAxisValue
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> if wantAxisName in self.location:
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> TypeError
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> :
28/04/2022 22:40:58 >   OUTPUT > ROBOFONT >> argument of type 'NoneType' is not iterable```

**Comment by LettError** [comment]
Maybe related to the new designspace spec in fonttools? That's going to take some digging.

**Comment by typemytype** [comment]
`location` became `designLocation`

https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/designspaceLib/__init__.py#L2216

`location` is deprecated

https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/designspaceLib/__init__.py#L281

**Comment by LettError** [comment]
That line still seems to return a location. Doesn't explain why the location is None. Anyway - will explore tomorrow :)

**Comment by typemytype** [comment]
the new api does not set any location anymore, just `descriptor.designLocation`
the deprecated `location` just returns `designLocation`

**Comment by LettError** [comment]
Yes, so my old code calls `location` which defers to `descriptor.designLocation` - You're saying there is no location at all? Where are the axis values stored?

**Comment by typemytype** [comment]
there is a fallback `.location` but it is never set in the reading class: `designLocation` is set
