### ISSUE TITLE
KeyedAxisDescriptor has no attribute 'axisOrdering'

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#35]
I originally thought the edits I was making on my other branch were causing this, but turns out it's on this master. This traceback comes up when I hit `Save`. Is the ordering of axes not supported anymore?

```
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 96, in sendEvent_
  File "/Applications/RoboFont-4_3b.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 507, in action_
    self.callback(sender)
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1912, in save
    self.finalizeSave(self.designSpacePath)
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1960, in finalizeSave
    self.doc.write(self.designSpacePath)
  File "/Applications/RoboFont-4_3b.app/Contents/Resources/lib/python3.7/fontTools/designspaceLib/__init__.py", line 2476, in write
    writer = self.writerClass(path, self)
  File "/Applications/RoboFont-4_3b.app/Contents/Resources/lib/python3.7/fontTools/designspaceLib/__init__.py", line 1291, in __init__
    self.effectiveFormatTuple = self._getEffectiveFormatTuple()
  File "/Applications/RoboFont-4_3b.app/Contents/Resources/lib/python3.7/fontTools/designspaceLib/__init__.py", line 1358, in _getEffectiveFormatTuple
    for axis in self.documentObject.axes
  File "/Applications/RoboFont-4_3b.app/Contents/Resources/lib/python3.7/fontTools/designspaceLib/__init__.py", line 1358, in <genexpr>
    for axis in self.documentObject.axes
AttributeError: 'NSKVONotifying_KeyedAxisDescriptor' object has no attribute 'axisOrdering'
```

**Comment by ryanbugden** [comment]
FYI, this bug doesn't happen on 4.2

**Comment by LettError** [comment]
No idea.

**Comment by typemytype** [comment]
different fontTools version with DS5

closing this in favor of https://github.com/LettError/designSpaceRoboFontExtension/tree/dse2.0
