### ISSUE TITLE
localisedStyleName bug

### ISSUE THREAD

**Issue by BlackFoundry** [LettError/designSpaceRoboFontExtension#4]
Hi,

Cannot save the .designspace as soon as an instance is added.

Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 169, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaBase.py", line 212, in action_
    self.callback(sender)
  File "/var/folders/c1/xh6vxzgj03q6tcw87m07slfh0000gn/T/tmpUpiG30/designSpaceRoboFontExtension-master/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1229, in save
  File "/var/folders/c1/xh6vxzgj03q6tcw87m07slfh0000gn/T/tmpUpiG30/designSpaceRoboFontExtension-master/DesignSpaceEditor.roboFontExt/lib/designSpaceEditorwindow.py", line 1276, in finalizeSave
  File "/var/folders/c1/xh6vxzgj03q6tcw87m07slfh0000gn/T/tmpUpiG30/designSpaceRoboFontExtension-master/DesignSpaceEditor.roboFontExt/lib/designSpaceDocument.py", line 962, in write
  File "/var/folders/c1/xh6vxzgj03q6tcw87m07slfh0000gn/T/tmpUpiG30/designSpaceRoboFontExtension-master/DesignSpaceEditor.roboFontExt/lib/designSpaceDocument.py", line 309, in write
  File "/var/folders/c1/xh6vxzgj03q6tcw87m07slfh0000gn/T/tmpUpiG30/designSpaceRoboFontExtension-master/DesignSpaceEditor.roboFontExt/lib/designSpaceDocument.py", line 399, in _addInstance
AttributeError: 'KeyedInstanceDescriptor' object has no attribute 'localisedStyleName'

**Comment by LettError** [comment]
This works I think. Can I close?
