### ISSUE TITLE
Anisotropic Instances

### ISSUE THREAD

**Issue by connordavenport** [LettError/designSpaceRoboFontExtension#55]
Hey! I have been playing around with DSE2 a lot recently and noticed that there are some issues with *viewing* the instances in the instancePreview. This is the most recent version on the branch. Here is the traceback:

```
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 88, in sendEvent_
  File "/Applications/RoboFont_444b.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 520, in action_
  File "/Users/connordavenport/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1104, in instancesEditorPreviewToolsCallback
  File "/Applications/RoboFont_444b.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 1454, in __init__
  File "/Users/connordavenport/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/instancesPreview.py", line 20, in build
  File "/Applications/RoboFont_444b.app/Contents/Resources/lib/python3.9/ufoProcessor/varModels.py", line 116, in makeInstance
  File "/Applications/RoboFont_444b.app/Contents/Resources/lib/python3.9/ufoProcessor/varModels.py", line 120, in _normalize
  File "/Applications/RoboFont_444b.app/Contents/Resources/lib/python3.9/fontTools/varLib/models.py", line 119, in normalizeLocation
  File "/Applications/RoboFont_444b.app/Contents/Resources/lib/python3.9/fontTools/varLib/models.py", line 63, in normalizeValue
TypeError: '<' not supported between instances of 'float' and 'tuple'

```

**Comment by typemytype** [comment]
oh was confusing with the "Labels Preview"

**Comment by connordavenport** [comment]
Yes, I will send you one privately. I noticed the issues with Mutator Sans as well.

**Comment by typemytype** [comment]
switching to mutatorMath for the instance preview helps... 

still dont know if varLib fully supports anisotropic locations

**Comment by typemytype** [comment]
should be solved in 7989cf9 by using mutatorMath for the instance previewer

**Comment by LettError** [comment]
@connordavenport can you see if your issue is resolved?

**Comment by typemytype** [comment]
this is solved along the way
