### ISSUE TITLE
Traceback when deleting family name from sources panel. 

### ISSUE THREAD

**Issue by LettError** [LettError/designSpaceRoboFontExtension#67]
```Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 89, in sendEvent_
  File "/Applications/RoboFont_4.4_release.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 520, in action_
  File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1694, in toolbarSave
  File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1648, in saveDesignspace
  File "/Users/erik/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1097, in unwrapSourceDescriptor
  File "objc/_convenience_mapping.pyc", line 18, in __getitem__objectForKey_
  File "objc/_convenience.pyc", line 134, in container_unwrap
KeyError: 'sourceFamilyName'
```

**Comment by typemytype** [comment]
this happens for every save? 

strange as sourceDescriptors are wrapped and unwrapped with the same keys

**Comment by typemytype** [comment]
https://github.com/LettError/designSpaceRoboFontExtension/commit/b7f9cd580404acb33e9d404536de366ba3c9b30e

this should fix it...
