### ISSUE TITLE
Traceback when editing existing postscript name

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#68]
UI freezes as well
```
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 89, in sendEvent_
  File "/Applications/RoboFont-4_4p.app/Contents/Resources/lib/python3.9/vanilla/vanillaList.py", line 54, in observeValueForKeyPath_ofObject_change_context_
  File "/Applications/RoboFont-4_4p.app/Contents/Resources/lib/python3.9/vanilla/vanillaList.py", line 767, in _edit
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1136, in instancesListEditCallback
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1059, in unwrapInstanceDescriptor
  File "objc/_convenience_mapping.pyc", line 18, in __getitem__objectForKey_
  File "objc/_convenience.pyc", line 134, in container_unwrap
KeyError: 'instancePostscriptFontName'
```
May be related to #67

**Comment by typemytype** [comment]
does this happen with the `locationPreview` branch? https://github.com/LettError/designSpaceRoboFontExtension/tree/locationPreview

**Comment by LettError** [comment]
I can reproduce this traceback in the master branch.

**Comment by typemytype** [comment]
https://github.com/LettError/designSpaceRoboFontExtension/commit/b7f9cd580404acb33e9d404536de366ba3c9b30e

this should fix it...
