### ISSUE TITLE
Sources list not updating properly when source is removed

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#79]
Getting this traceback when trying to remove a source from the list. It's not removed from the list. Will look into this a bit more deeply later to see how I can reliably reproduce.

```
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 88, in sendEvent_
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 520, in action_
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 1042, in sourcesToolsCallback
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py", line 112, in removeSource
ValueError: list.remove(x): x not in list
```

**Comment by typemytype** [comment]
do you have the latest version? the line numbers doesn't match up anymore and I made some changes to reverse the selection while removing items for that list: https://github.com/LettError/designSpaceRoboFontExtension/blob/master/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py#L1146-L1148

**Comment by ryanbugden** [comment]
Looks like mine is 2.1 but with some other differences, like requiring 4.3 instead of 4.5b. Will update manually!

**Comment by ryanbugden** [comment]
Just tried to reproduce and can't. Closing for now, thanks for bearing with me!
