### ISSUE TITLE
/? /! still not working

### ISSUE THREAD

**Issue by jeremymickel** [LettError/designSpaceRoboFontExtension#81]
This isn't working for me (in Single Window Mode, FYI). Getting this traceback:

```
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaEditText.py", line 11, in controlTextDidChange_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 539, in action_
  File "/Users/jeremymickel/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/locationPreview.py", line 244, in inputCallback
NameError: name 'CurrentGlyph' is not defined
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaEditText.py", line 11, in controlTextDidChange_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 539, in action_
  File "/Users/jeremymickel/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/locationPreview.py", line 244, in inputCallback
NameError: name 'CurrentGlyph' is not defined
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 88, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaEditText.py", line 11, in controlTextDidChange_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 539, in action_
  File "/Users/jeremymickel/Library/Application Support/RoboFont/plugins/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/locationPreview.py", line 244, in inputCallback
NameError: name 'CurrentGlyph' is not defined

```

_Originally posted by @jeremymickel in https://github.com/LettError/designSpaceRoboFontExtension/issues/77#issuecomment-1887539711_

**Comment by typemytype** [comment]
shortly after adding support for `/?/!` I fixed this already :)

https://github.com/LettError/designSpaceRoboFontExtension/commit/3b469e5e192ad0dafe853b61ebd6fb99156da15a

could you reinstall this extension? thanks

**Comment by jeremymickel** [comment]
You're right. Sorry!
